### PR TITLE
Feat/Fix: mrgnhnt96

### LINKED ISSUE #9: Exclude getters by default
Just came across your package, it looks super useful and I'm really interested in using it.

Ran a couple of use cases and found that the `_autoequalProps` includes getter methods by default. I think that the ability to include getter methods is useful but should not be default. I use getter methods as a way of extending the functionality to my classes with the data/fields already provided, not necessarily as a new prop.

A possible solution for this would be to add an option to the `build.yaml` file

```yaml
targets:
  $default:
    builders:

      autoequal_gen|autoequal:
        enabled: true
        options:
          include_getters: true
```

Or to annotate the element with either `@ignoreAutoequal` or `@includeAutoequal` for one off scenarios

The reason that getters (and setters, but I'll create another ticket for that) are included is because they are technically `FieldElement`s, with a distinguishable flag, `isSynthetic`. A simple check [here][1] to exclude the element from the list should solve this issue.

<details>

<summary>Here is a minimum code example</summary>

My dart class
```dart
import 'package:autoequal/autoequal.dart';
import 'package:equatable/equatable.dart';

part 'fake_class.g.dart';

@autoequal
class FakeClass extends Equatable {
  const FakeClass({
    required this.a,
  });

  final String a;

  String get b => 'b';

  @override
  List<Object?> get props => _autoequalProps;
}
```

Generated Code
```dart
// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'fake_class.dart';

// **************************************************************************
// AutoequalGenerator
// **************************************************************************

extension _$FakeClassAutoequal on FakeClass {
  List<Object?> get _autoequalProps => [a, b];
}

```
</details>

[1]: https://github.com/SunnyDayDev/autoequal/blob/main/autoequal_gen/lib/src/generator.dart#:~:text=%3D%3E%20!(-,element.isStatic,-%7C%7C

### LINKED ISSUE #10: Ignore Setter methods
Cont. from #9 

Looks like `_autoequalProps` includes setter methods, even when there is no getter method provided.

The reason that setters are included is because they are technically `FieldElement`s, with a distinguishable flag, `isSynthetic`. A simple check [here][1] to exclude the element from the list should solve this issue.

<details>

<summary>Here is a minimum code example</summary>

My dart class
```dart
import 'package:autoequal/autoequal.dart';
import 'package:equatable/equatable.dart';

part 'fake_class.g.dart';

@autoequal
class FakeClass extends Equatable {
  const FakeClass({
    required this.a,
  });

  final String a;

  set c(String value) => print(value);

  @override
  List<Object?> get props => _autoequalProps;
}
```

Generated Code
```dart
// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'fake_class.dart';

// **************************************************************************
// AutoequalGenerator
// **************************************************************************

extension _$FakeClassAutoequal on FakeClass {
  List<Object?> get _autoequalProps => [a, c];
}
```
</details>

[1]: https://github.com/SunnyDayDev/autoequal/blob/main/autoequal_gen/lib/src/generator.dart#:~:text=%3D%3E%20!(-,element.isStatic,-%7C%7C

### PR DESCRIPTION
**Pull request by mrgnhnt96**
Hey @SunnyDayDev!

This is a large PR, if you'd like for me to break it into smaller PRs, I definitely can.

Here is a breakdown of the PR:

## Features

- Allow abstract classes
  - totally understand your reasoning in #5, but I think that this is a good feature to have. The developers that use this package should have an understanding of what they are doing. If they want to generate the props for an abstract class, which will more than likely be re-used in subclasses, then they should be able to.
- Check for Inheritance
  - If a class extends another class that uses Equatable, then the props will be generated without the need of extending Equatable or using the mixin EquatableMixin.
    - This was not an issue if the super class extended Equatable, only when the super class used the equatable mixin.
  - This also allows for super prop generation for `autoequalMixin` classes.
- Auto handle mixins
  - If a class uses the mixin EquatableMixin, then the props will be generated without the need of annotating with `@autoequalMixin`.
    - The class can continue to be annotated with `autoequalMixin` to force the generation of the autoequal mixin.
- Change `_autoequalProps` to `_$props`
  - This change is to follow generation convention, by including the leading underscore and the trailing dollar sign.
    - `_autoequalProps` is still supported, annotated with `@Deprecated`. Which can be removed in a future release.
- Additional field checks
  - Check to see if the field has a getter
    - If none, the field will be ignored.
    - Fixes #10
  - Check for synthetic fields
    - If the field is a getter, then it will be ignored.
      - Unless the field is annotated with `@includeAutoequal`.
    - Fixes #9
- Add global option to include/ignore getter methods
  - Fixes #9
  - Within the `build.yaml` file, the following option is supported

```yaml
targets:
  $default:
    builders:

      autoequal_gen:
        enabled: true
        options:
          include_getters: true # default is false
```

- Add scope to exports
  - Currently all classes and constants are exported from `autoequal`. By adding a scope, we can reduce the possible dev confusion of having multiple options
    - Only export the following
      - `autoequal`
      - `autoequalMixin`
      - `includeAutoequal`
      - `ignoreAutoequal`
- Add Targets to annotation classes
  - Helps the analyzer to determine where the annotation can be used.
    - `autoequal` can only be used on classes
    - `autoequalMixin` can only be used on classes
    - `includeAutoequal` can only be used on fields & getters
    - `ignoreAutoequal` can only be used on fields & getters
- Change builder name from `autoequal` to `autoequal_gen`
  - This is to follow the convention of other builders, such as `json_serializable` and `freezed`.
  - by keeping the builder name the same as the project, configuring the build.yaml file is simpler
    - Current config: `autoequal_gen|autoequal`
    - New config: `autoequal_gen`
- Add warnings when `props` method is not implemented
  - This warning is printed to console only when annotated with `@autoequal` and
    - extending `Equatable` and props is not implemented
    - inheriting from a class that uses `Equatable` and props is not implemented
- Add Tests
  - The previous test files were only testing the work of equatable and not so much of the generated code. So I re-wrote the tests to test each case individually for extends, extends with mixin, and mixin only scenarios.
    - Use cases
      - abstract
      - basic
      - getter
      - ignore
      - include getter
      - inherited
      - inherited none
      - private
      - setter
      - static
- Update README
  - Update the README to reflect the changes made in this PR.

I know this is a lot, so please let me know if you have any questions or concerns. I'm happy to make any changes that you would like.

### CODE REVIEW

**Comment by SunnyDayDev** [comment]
Hey @mrgnhnt96!
I'm too busy on weekdays so I'll check the PR on the weekend.

I'm in anticipation, it seems to be a great work.

**Comment by SunnyDayDev** [comment]
Hey @mrgnhnt96!
I checked the PR. You have done the excellent work!

Most of changes are great and good quality. With the exception of the moment which we have to discuss.

**Comment by SunnyDayDev** [comment]
What you think, is it a good idea to change the API? I mean the renaming `_autoequalProps` to `_$props`.

Why the `_$props` is better than `_autoequalProps`? Is it just shorter or  better fits the dart/flutter code convention?

File: test_project/lib/extends/getter.dart [hunk 1]
```diff
@@ -0,0 +1,14 @@
+import 'package:autoequal/autoequal.dart';
+import 'package:equatable/equatable.dart';
+
+part 'getter.g.dart';
+
+@autoequal
+class Getter extends Equatable {
+  const Getter();
+
+  set one(String newValue) => print(newValue);
```
Comment (SunnyDayDev) [inline test_project/lib/extends/getter.dart]: It seems that it should be getter instead of a setter

```suggestion
  String get one => 'one';
```

File: test_project/lib/extends_with_mixin/getter.dart [hunk 2]
```diff
@@ -0,0 +1,11 @@
+import 'package:autoequal/autoequal.dart';
+import 'package:equatable/equatable.dart';
+
+part 'getter.g.dart';
+
+@autoequalMixin
+class Getter extends Equatable with _$GetterAutoequalMixin {
+  const Getter();
+
+  set one(String newValue) => print(newValue);
```
Comment (SunnyDayDev) [inline test_project/lib/extends_with_mixin/getter.dart]: Same here. It seems that it should be getter instead of a setter

```suggestion
  String get one => 'one';
```

File: test_project/lib/mixin/getter.dart [hunk 3]
```diff
@@ -0,0 +1,11 @@
+import 'package:autoequal/autoequal.dart';
+import 'package:equatable/equatable.dart';
+
+part 'getter.g.dart';
+
+@autoequal
+class Getter with EquatableMixin, _$GetterAutoequalMixin {
+  const Getter();
+
+  set one(String newValue) => print(newValue);
```
Comment (SunnyDayDev) [inline test_project/lib/mixin/getter.dart]: And this one.

```suggestion
  String get one => 'one';
```

**Review by SunnyDayDev — CHANGES_REQUESTED** [review]
Hey @mrgnhnt96!
I checked the PR. You have done the excellent work!

Most of changes are great and good quality. With the exception of these small issues.

**Comment by SunnyDayDev** [comment]
I like the way that you solved mentioned issues. You even added the ability to use abstract classes in a good way, so I'm ready to agree that it's a necessary feature.

**Comment by mrgnhnt96** [comment]
😅 Nice catches, those have been fixed and pushed to the branch 👍

**Review by SunnyDayDev — APPROVED** [review]
Now it's quite good)

**Comment by SunnyDayDev** [comment]
I'll update CHANGELOG, set up CI to run tests with the new test project, and then publish the new version to pub.dev.

**Comment by SunnyDayDev** [comment]
@mrgnhnt96
I have a question for you. For the past two years, I haven't touched Flutter at all, except for minimal library support. I'm currently focused on Android native development and KMM, so my Dart/Flutter expertise is fading away.

Do you want to become a library maintainer? Your current changes are totally good, I liked your vision of the project, and, in my opinion, you are the one who can develop the project in right way.

**Comment by mrgnhnt96** [comment]
@SunnyDayDev
I'd be happy to! I know that maintaining packages can be hard, especially if you're no longer really using it, even more the language. So I'm more than willing to help you out here!

Transferring the project on pub.dev shouldn't be too hard. You'll need to add me as a publisher via email (mrgnhnt96@gmail.com), then we can transfer the project to me.

For the repo, you can go into repo settings and click on transfer repo, and you'd put in my username, @mrgnhnt96.
